#!/bin/bash
# script to build and run the css-parser

BUILDSCRIPTDIR="`dirname $0`";
PRJROOT="${BUILDSCRIPTDIR}/.."

MINPARAMS=1
StyleSheet=$1
MainFile="cases/StyleParserTest.hx"
Force=false
Resource=""
Debug=""

#parse arguments
while getopts "n:ms:tfd" OptionName
	do
		case $OptionName in
			n ) MainFile=${OPTARG};;
			s ) StyleSheet=${OPTARG};;
			f ) Force=true;;
			d ) Debug="-debug";;
	esac
done

MainClass=${MainFile//\//.}
MainClass=${MainClass%.hx}
Parser="test.n"

echo "MainFile: ${MainFile}"
echo "MainClass: ${MainClass}"
echo "StyleSheet: ${StyleSheet}"

if [[ -f ${StyleSheet} ]] ; then
	Resource="-resource ${StyleSheet}@stylesheet"
fi;

if ${Force} || [[ ! -f ${Parser} ]]  ||  test ${MainFile} -nt ${Parser}  ||  test ${StyleSheet} -nt ${Parser} ; then
	echo "Compiling parser"
	
	haxe build-parser.hxml -main ${MainClass} -neko ${Parser} ${Resource} --no-inline ${Debug} &&
	neko ${Parser}
else
	neko ${Parser}
fi;
